### ISSUE TITLE
程序异常

### ISSUE THREAD

**Issue by K8721** [FindAllTeam/FindAll#1]
在执行本地扫描的时候提示程序异常。提示检测错误，Agent打开异常
<img width="388" alt="00ae533a6e5b8678ddecebe35fb82b2" src="https://github.com/FindAllTeam/FindAll/assets/157349952/b12f03cd-30e4-4e48-9731-f780f636cf2e">

**Comment by K8721** [comment]
虚拟机里管理员权限执行的程序

**Comment by Xutaotaotao** [comment]
https://github.com/FindAllTeam/FindAll/releases/tag/v1.2.0
