### ISSUE TITLE
严重问题，系统卡死，CPU跑满

### ISSUE THREAD

**Issue by Bluecap666** [FindAllTeam/FindAll#3]
**名称:** [输入Issue名称]

**类别:** [Bug还是Feature或者其他的类别]

**描述:** [请描述背景，可能的原因，如何重现问题]

**系统环境:** [说明什么系统运行环境，系统版本]

**用户角色:** [是普通用户还是Administrator用户]

**相关issue:** [是否有类似关联的issue，可以罗列在这里]

**其他:** [其他描述]

**Comment by Xutaotaotao** [comment]
https://github.com/FindAllTeam/FindAll/releases/tag/v1.2.0
