### ISSUE TITLE
程序运行后，提示检测错误，Agent打开异常

### ISSUE THREAD

**Issue by ogierJACK** [FindAllTeam/FindAll#4]
**名称:** [输入Issue名称]
程序运行后，提示检测错误，Agent打开异常
**类别:** [Bug还是Feature或者其他的类别]
BUG
![微信截图_20240204110855](https://github.com/FindAllTeam/FindAll/assets/69137425/c186594e-b421-463c-8f98-aa8542db6e8d)
![微信截图_20240204111704](https://github.com/FindAllTeam/FindAll/assets/69137425/690ac2f2-9b3d-4df1-afbf-0212a889bece)

**描述:** [请描述背景，可能的原因，如何重现问题]
打开程序后，点击本机扫描分析“点击开始”后弹出报错界面
**系统环境:** [说明什么系统运行环境，系统版本]
win10和windows server 2022
**用户角色:** [是普通用户还是Administrator用户]
Administrator用户
**相关issue:** [是否有类似关联的issue，可以罗列在这里]

**其他:** [其他描述]

**Comment by Xutaotaotao** [comment]
https://github.com/FindAllTeam/FindAll/releases/tag/v1.2.0
