### ISSUE TITLE
可以支持导入和导出findall里面获取到的信息吗？

### ISSUE THREAD

**Issue by Huck-Lim** [FindAllTeam/FindAll#7]
试用情景：一人去客户现场，把该信息采完后，共享给其他人一起进行分析。
要是有个接口支持导入，别人使用的时候，也可以根据接口，写个脚本去获取信息进行初步排查。要是也可以使用官方的脚本去获取信息，再导入查看，就更好了。因为这个工具的UI设计，看起来真的爽！

**Comment by Xutaotaotao** [comment]
师傅进群沟通，加群主，详细说一下你的需求！！！

**Comment by Huck-Lim** [comment]
不好意思看错了，是支持该功能的。
